backend:
  replicas: 1
  port: 80

  image:
    repository: agg
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 80

frontend:
  replicas: 1
  port: 3000

  image:
    repository: fe
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 3000

nameOverride: ""
fullnameOverride: ""

