deployment:
  replicas: 1
  port: 80
  dbUrl: ""
  apiKey: ""

image:
  repository: agg
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""