apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "aggregator.selectorLabels" (dict "ctx" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aggregator.selectorLabels" (dict "ctx" . "component" "backend") | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: DB_URL
              value: "{{ .Values.backend.dbUrl }}"
            - name: API_KEY
              value: "{{ .Values.backend.apiKey }}"