apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aggregator.selectorLabels" (dict "ctx" . "component" "backend") | nindent 4 }}
