kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  type: ExternalName
  externalName: postgresql.postgresql-local.svc.cluster.local
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432