apiVersion: v1
kind: Service
metadata:
  name: {{ include "aggregator.fullname" . }}-frontend
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "aggregator.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
