apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aggregator.fullname" . }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "aggregator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aggregator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.deployment.port }}"
            - name: DB_URL
              value: "{{ .Values.deployment.dbUrl }}"
            - name: API_KEY
              value: "{{ .Values.deployment.apiKey }}"