# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#   name: postgresql
#   labels:
#     # You should set the "kubernetes.io/service-name" label.
#     # Set its value to match the name of the Service
#     kubernetes.io/service-name: postgresql
# addressType: IPv4
# ports:
#   - protocol: TCP
#     port: 5432
# endpoints:
#   - addresses:
#       - "192.168.100.23"
# ---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql 
subsets: 
  - addresses:
    - ip: 192.168.100.23
    ports:
    - port: 5432